### ISSUE TITLE
i am noob

### ISSUE THREAD

**Issue by PyerreIA12** [Zeturic/bpre-move-item#1]
how can i resolve this?
![image](https://user-images.githubusercontent.com/71110798/93651426-ca98e200-f9e7-11ea-8329-aa3ca915168b.png)

**Comment by Zeturic** [comment]
Did you read through the linked [gist](https://gist.github.com/Zeturic/db1611cc7b17c3140f9b9af32e1b596b) on how to set up your environment? A POSIX shell is required. Powershell does not work.

Also, regardless, it looks like you didn't run `build_tools.sh`.

**Comment by Zeturic** [comment]
Since there's been no response and the problem seems to just be a misconfigured environment and not actually an issue with the repository, I'm going to go ahead and close this.

Remember that you can still comment - even on closed issues - and I'll definitely help if you do so.
